name: Yaloi
favicon: null
layout_spectrum: 0.8662368559744209
typography_spectrum: 0.8079770337790251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.24333339044824243
  lightness: 0.6292594426777214
  saturation: 0.4847016902640462
  rhythmicContrast: 0.015127258375287056
purpose: []
